name: Docker build

on:
  push:
    branches:
      - *
    tags:
      - *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: aroq/awscli2-k8s-tools
          tag_with_ref: true
          tag_with_sha: true
